/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GameWindow {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface RollDice {
        /**
          * The value of the dice
         */
        "value": number;
    }
    interface TestComponent {
        /**
          * Label of the button
         */
        "label": string;
        /**
          * Value of the button
         */
        "value": number;
    }
}
declare global {
    interface HTMLGameWindowElement extends Components.GameWindow, HTMLStencilElement {
    }
    var HTMLGameWindowElement: {
        prototype: HTMLGameWindowElement;
        new (): HTMLGameWindowElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLRollDiceElement extends Components.RollDice, HTMLStencilElement {
    }
    var HTMLRollDiceElement: {
        prototype: HTMLRollDiceElement;
        new (): HTMLRollDiceElement;
    };
    interface HTMLTestComponentElement extends Components.TestComponent, HTMLStencilElement {
    }
    var HTMLTestComponentElement: {
        prototype: HTMLTestComponentElement;
        new (): HTMLTestComponentElement;
    };
    interface HTMLElementTagNameMap {
        "game-window": HTMLGameWindowElement;
        "my-component": HTMLMyComponentElement;
        "roll-dice": HTMLRollDiceElement;
        "test-component": HTMLTestComponentElement;
    }
}
declare namespace LocalJSX {
    interface GameWindow {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface RollDice {
        /**
          * The value of the dice
         */
        "value"?: number;
    }
    interface TestComponent {
        /**
          * Label of the button
         */
        "label"?: string;
        /**
          * Value of the button
         */
        "value"?: number;
    }
    interface IntrinsicElements {
        "game-window": GameWindow;
        "my-component": MyComponent;
        "roll-dice": RollDice;
        "test-component": TestComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "game-window": LocalJSX.GameWindow & JSXBase.HTMLAttributes<HTMLGameWindowElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "roll-dice": LocalJSX.RollDice & JSXBase.HTMLAttributes<HTMLRollDiceElement>;
            "test-component": LocalJSX.TestComponent & JSXBase.HTMLAttributes<HTMLTestComponentElement>;
        }
    }
}
